"""
merge_assess.snake
Matthew Stone <mstone5@mgh.harvard.edu>

"""

configfile: 'config.yaml'

include: 'rules/pesr_preprocessing.rules'
include: 'rules/depth_preprocessing.rules'
include: 'rules/preprocessing_qc.rules'

import pandas as pd

BATCH_KEY = pd.read_table(config['batches'], dtype=str)
BATCHES = sorted(BATCH_KEY.batch.unique())

with open(config['groups']) as glist:
    GROUPS = [g.strip() for g in glist.readlines()]

PESR_SOURCES = config['pesr_sources']
CNV = config['cnv_types']

wildcard_constraints:
    svtype='(' + '|'.join(CNV) + ')'

rule all:
    input:
        expand('filtered_vcfs/{source}.{group}.vcf.gz',
               source=PESR_SOURCES, group=GROUPS),
        #'qc/aggregate/raw_counts.txt',
        #'qc/aggregate/filtered_counts.txt',
        #expand('std_beds/{batch}.{svtype}.bed.gz',
        #       batch=BATCHES, svtype=CNV)

